#ifndef COLORSMITH_VERSION_H
#define COLORSMITH_VERSION_H

#define COLORSMITH_VERSION_MAJOR 1
#define COLORSMITH_VERSION_MINOR 0
#define COLORSMITH_VERSION_PATCH 0
#define COLORSMITH_VERSION_STRING "1.0.0"

#define COLORSMITH_APP_NAME "ColorSmith"
#define COLORSMITH_ORGANIZATION_NAME "Ktechpit"
#define COLORSMITH_ORGANIZATION_DOMAIN "ktechpit.com"

#endif // COLORSMITH_VERSION_H
