name: colorsmith
version: '1.1.0'
summary: Professional color management suite for designers and developers
description: |
  ColorSmith is a professional color management suite designed for designers, developers, 
  and digital artists. It delivers precision tools for color selection, WCAG-compliant 
  accessibility testing, gradient creation, and comprehensive palette management.

  Key Features:
  • WCAG AA/AAA compliant contrast checker for accessible design
  • Screen color picker with system-wide capture
  • Interactive HSV color plane with visual HSL gradient sliders
  • Support for HEX, RGB, RGBA, HSL, HSLA, HSV, and CMYK formats
  • Smart paste detection that auto-converts color codes
  • Gradient generator with CSS, SVG, and PNG export
  • Palette management with image extraction and JSON import/export
  • Comprehensive keyboard shortcuts and customizable layout
  • Professional workflow tools with persistent settings

grade: stable
confinement: strict
base: core24
compression: lzo

icon: snap/gui/icon.png

platforms:
  amd64:
  arm64:

apps:
  colorsmith:
    command: usr/bin/colorsmith
    desktop: usr/share/applications/com.ktechpit.colorsmith.desktop
    common-id: com.ktechpit.colorsmith
    extensions:
      - kde-neon-6
    plugs:
      - home
      - network
      - opengl

parts:
  colorsmith:
    source: .
    plugin: cmake
    build-packages:
      - libxkbcommon-dev

    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr

    override-build: |
      craftctl default

      # Fix desktop icon path for snapped environment
      sed -i \
        "s|^Icon=.*|Icon=\${SNAP}/meta/gui/icon.png|" \
        ${CRAFT_PART_INSTALL}/usr/share/applications/com.ktechpit.colorsmith.desktop

    prime:
      - -usr/include
      - -usr/lib/*/cmake
      - -usr/share/ECM
      - -usr/share/man
      - -usr/share/lintian
